name: Build and deploy website

on: [push]

jobs:
    # Build website and artifact
    build:

        runs-on: ubuntu-24.04

        name: "Build website"

        steps:

        - name: checkout course_GEO4-4436
          uses: actions/checkout@v4

        - uses: mamba-org/setup-micromamba@v2
          with:
              environment-name: action
              create-args: >-
                  python
                  jupyter-book
                  cmake
              init-shell: bash

        - name: Configure
          shell: bash -l {0}
          run: |
              mkdir build
              cmake \
                  -S . \
                  -B build

        - name: Build html
          shell: bash
          run: |
              cmake --build build

        # see: https://github.com/actions/upload-pages-artifact
        - name: Archive artifact
          shell: bash -l {0}
          run: |
            tar \
              --dereference --hard-dereference \
              --directory "build/course/_build/html/" \
              -cvf "$RUNNER_TEMP/artifact.tar" \
              .

        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: github-pages
            path: ${{ runner.temp }}/artifact.tar
            retention-days: 1
            if-no-files-found: error

    # see: https://github.com/actions/deploy-pages
    deploy:
        needs: build

        name: "Deploy website"

        # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
        permissions:
            pages: write      # to deploy to Pages
            id-token: write   # to verify the deployment originates from an appropriate source

        # Deploy to the github-pages environment
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        # Specify runner + deployment step
        runs-on: ubuntu-24.04
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4 # or the latest "vX.X.X" version tag for this action
